import requests
from bs4 import BeautifulSoup

# List of URLs to scrape (provided by you)
url_list = [
    "https://www.rogerebert.com/festivals-and-awards/tiff-2019-joker-uncut-gems",
    "https://www.rogerebert.com/reviews/joker-movie-review-2019",
    "http://www.reelviews.net/reelviews/joker",
    "https://www.bfi.org.uk/news-opinion/sight-sound-magazine/reviews-recommendations/joker-todd-phillips-joaquin-phoenix",
    "https://www.sfexaminer.com/entertainment/joker-a-dark-gritty-powerful-drama-about-rage/",
    "https://www.nytimes.com/2019/10/03/movies/joker-review.html",
    "https://www.nytimes.com/2019/10/07/movies/joker-movie-reviews.html",
    "https://www.nytimes.com/2019/10/09/movies/joker-movie-controversy.html",
    #"https://www.washingtonpost.com/goingoutguide/movies/joaquin-phoenix-is-a-vivid-operatic-joker-but-the-movie-is-way-too-full-of-itself/2019/10/01/a95e53a4-dfd5-11e9-b199-f638bf2c340f_story.html?arc404=true",
    "https://www.flickfilosopher.com/2019/10/joker-movie-review-sad-clown-bad-clown-not-at-all-a-rad-clown.html",
    "https://1001moviesreviewed.wordpress.com/2019/10/22/joker-2019/",
    "https://150film.blogspot.com/2019/10/114-joker.html",
    "https://www.2filmcritics.com/post/joker",
    "https://www.20min.ch/entertainment/kino/story/Von-gesellschaftlichen-Aussenseitern-15699622",
    "https://3brothersfilm.com/blog/2019/10/9/review-joker-2019",
    "https://4columns.org/pinkerton-nick/joker",
    "https://812filmreviews.com/2019/09/12/tiff-review-joker/",
    "http://www.aconstantlyracingmind.com/2019/10/joker-review.html",
    "http://www.afilmlife.com/joker.html",
    "https://www.apotpourriofvestiges.com/2019/10/todd-phillips-joker-review-rise-of-joker.html",
    "https://asliveroffilm.blogspot.com/2019/10/no-88-2019-joker-october-7th.html",
    "https://www.ayardstickforlunatics.com/main/3klsljyrvorrf0c9ry5go1hpgqvpj8",
    "http://asbvirtualinfo.blogspot.com/2019/10/critica-pelicula-joker-todd-phillips.html",
    "http://www.alleyways.de/abgeschminkt/2019/joaquin-phoenix-joker/",
    "https://www.youtube.com/watch?v=CW42Av-YphA&feature=youtu.be",
    "https://www.actionfreunde.de/joker/",
    "http://www.activecontext.net/joker-2019/",
    "https://aisleseat.com/joker.html",
    "https://www.almodon.com/culture/2019/10/13/%D8%AC%D9%88%D9%83%D8%B1-%D8%AA%D9%88%D8%AF-%D9%81%D9%8A%D9%84%D9%8A%D8%A8%D8%B3-%D9%85%D8%B5%D8%A7%D8%B5-%D8%AF%D9%85%D8%A7%D8%A1%D8%8C-%D9%8A%D8%AA%D8%BA%D8%B0%D9%89-%D8%B9%D9%84%D9%89-%D8%A3%D9%81%D9%84%D8%A7%D9%85-%D8%A3%D8%AE%D8%B1%D9%89",
    "https://www.youtube.com/watch?v=zWgtnUS0R3E&t=11s",
    "https://aldmovieland.blogspot.com/2019/12/joker-2019.html",
    "https://aleteia.org/2019/10/04/joker-redeems-itself-by-asking-am-i-my-brothers-keeper/",
    "https://alibi.com/film/59551/Joker.html",
    "http://allofcinema.com/dzhoker-joker-2019/",
    "https://allthatcinema.wordpress.com/2019/09/04/venezia-76-joker/",
    "https://allusionsofgrandeurblog.wordpress.com/2019/10/09/joker-cuck/",
    "https://www.alohacriticon.com/cine/criticas-peliculas/joker-2019-de-todd-phillips/",
    "https://altapeli.com/critica/review-joker-guason/",
    "https://alwaysgoodmovies.com/reviews/joker-2019",
    "https://amazingcinema.it/joker/",
    "https://anawadhboyspanorama.wordpress.com/2020/08/13/why-we-need-to-reassess-narratives-around-crime-in-popular-culture/",
    "https://anawadhboyspanorama.wordpress.com/2020/08/23/reassessing-narratives-around-violence-in-popular-culture-part-2/",
    "https://anawadhboyspanorama.wordpress.com/2023/08/25/the-horror-and-the-humanity-part-2/",
    "https://anopinionortwo.wordpress.com/2019/10/09/joker/",
    "https://portalanalitika.me/clanak/344664/dzoker-ni-za-ciji-rukav",
    "https://andersonvision.com/in-a-society-where-joker-is-too-smart-review/",
    "https://zummer.blogspot.com/2020/05/second-guessing-which-films-got-bbfc.html",
    "http://anotherfilmanotherplanet.com/2019/10/18/joker-critique/",
    "https://another-film-critic.blogspot.com/search?q=joker",
    "http://anthonysfilmreview.com/Film/J/Joker.htm",
    "http://anygoodfilms.com/joker-review/",
    "https://apokalypsefilm.com/2019/10/15/kritik-joker/",
    "https://areyouscreening.com/2019/10/18/movies/joker-review-the-origin-story-of-someone/",
    "http://www.arrobanerd.com.br/coringa-critica/",
    "https://www.artechock.de/film/text/kritik/j/joker0.htm",
    "https://artsforum.ca/film/at-theaters/at-theaters-3-0",
    "http://www.asburymovies.it/2019/10/01/joker/",
    "https://www.withashleyandco.com/2019/10/joker-movie-review/",
    "https://assholeswatchingmovies.com/2019/10/04/lets-talk-about-joker/",
    "https://assholeswatchingmovies.com/2019/09/11/tiff19-joker/",
    "https://www.youtube.com/watch?v=J_wqtMpyRTg&t=27s",
    "https://www.attackfromplanetb.com/2019/10/joker-2019-usa-canada-review/",
    "https://audiovisuellblog.com/2019/10/21/im-kino-joker-kritik-review/",
    "http://maugsberger.blogspot.com/2019/12/joker-review.html",
    "https://www.austinchronicle.com/events/film/2019-10-04/joker/",
    "http://awmoviespot.com/2019/12/01/joker-2019-review/",
    "https://awardswatch.com/review-todd-phillips-joker-is-dark-gritty-and-fearless-phoenix-is-mesmerizing/",
    "https://awardswatch.com/toronto-review-joker-is-a-magnetic-volcanic-masterpiece/",
    "https://awardswatch.com/venice-review-joker-is-joaquin-phoenixs-glorious-dance-of-madness/",
    "https://www.youtube.com/watch?v=yWGBL5hlhOM",
    "https://backtothemovies.com/joker-review-a-film-made-by-adults-for-adults/",
    "https://badfeelingmag.com/2019/09/11/tiff-2019-review-joker-is-an-unsettling-violent-revenge-fantasy/",
    "http://basementrejects.com/review/joker-2019/",
    "https://battleroyalewithcheese.com/2019/10/caillous-take-on-joker/",
    "https://battleroyalewithcheese.com/2019/10/joker-the-brwc-review/",
    "https://beforethecyborgs.com/film/review-joker-2019/",
    "https://www.youtube.com/watch?v=WBWxtYVYEAo",
    "http://bigfanboy.com/wp/?p=34298",
    "https://bigshinyrobot.com/movies/joker-roundtable-review/",
    "https://erdincbozkurt.wordpress.com/2020/03/23/kac-kisiyi-oldurdum-duslerimde-joker/",
    "https://www.bilimkurgukulubu.com/sinema/film-incelemeleri/joker-popcorn-sanat-filmlerinin-donusu/",
    "https://www.bina007.com/2019/10/joker.html",
    "https://www.birgun.net/haber/joker-cassandra-sendromu-271387",
    "https://www.blairwitch.de/moviebase/2749/Joker/Kritik/",
    "https://elblocdejosep.blogspot.com/2019/11/guasada.html",
    "https://blog.dnevnik.hr/stankagj/2019/11/1632264343/joker.html",
    "http://bloodbrothersfilmreviews.blogspot.com/2019/10/joker-2019.html",
    "https://www.blu-ray.com/Joker/923009/#Review",
    "https://blu-ray-rezensionen.net/joker-4k-uhd/",
    "https://movieguy1970.blogspot.com/2019/10/joker-2019.html",
    "https://www.bollacos.com/joker-fascinacion/",
    "http://boomuk.net/joker.html",
    "https://bostonhassle.com/review-joker-2019-dir-todd-philips/",
    "https://www.youtube.com/watch?v=jhAHEBBLPQ0",
    "https://www.breitbart.com/entertainment/2019/10/04/joker-review-todd-phillips-blasts-americas-bitter-jealous-violent-fascist-woketards/",
    "https://brieftake.com/joker-review/",
    "https://www.youtube.com/watch?v=ypr_0WexlbA",
    "https://www.bulletproofaction.com/2019/10/05/bullet-points-joker/",
    "http://www.bullz-eye.com/2019/10/07/movie-review-joker/",
    "https://butwhythopodcast.com/2019/10/04/review-joker-feels-subpar-despite-a-stellar-lead-performance/",
    "http://c7nema.net/critica/item/51643-joker--por-rodrigo-fonseca.html",
    "https://cadernodoescritor.blogspot.com/2019/10/joker-imoralidade-da-justica.html",
    "https://cailloupettismoviereviews.com/2019/10/05/joker-film-review/",
    "https://www.youtube.com/watch?v=6T88UksaH6g&feature=youtu.be",
    "http://www.cambridgeday.com/2019/10/02/joker-phoenix-tries-to-hold-it-all-together-but-eventually-film-lets-loose-breaks-down/",
    "https://carlocarrasco.com/2019/10/10/carlo-carrascos-movie-review-joker/",
    "http://carstairsconsiders.blogspot.com/2022/08/movie-review-joker-2019.html",
    "https://www.caseymoviemania.com/2019/09/joker-2019-review/",
    "https://www.cautionspoilers.com/film-reviews/joker/",
    "https://celebmix.com/film-review-joker-a-film-that-leaves-you-thinking/",
    "https://cenasdecinema.com/coringa/",
    "http://www.centerfieldofgravity.com/joker/",
    "https://www.cervenykoberec.cz/124587/recenze-joker-psychopaticky-joker-se-rodi-ze-socialni-nestability-antihrdinou-je-mesto-gotham/",
    "https://www.cgmagonline.com/review/movie/tiff-2019-review-joker/",
    "https://youtube.com/watch?v=ChLTgapUxUw",
    "https://www.chasewhale.com/film/joker",
    "https://chrishunneysett.uk/2019/09/22/joker/",
    "https://www.youtube.com/watch?v=1gzdlfCp2Iw",
    "https://christophhartung.de/index.php?page=todd-phillips-joker-joaquin-phoenix",
    "https://cinedivergente.com/joker/",
    "https://www.cineenserio.com/joker-el-rey-de-la-comedia/",
    "https://cinegrandiose.com/2019/10/01/joker-analise-e-impressao/",
    "https://cinemusefilms.com/2019/11/06/joker-2019/",
    "https://www.cineyliteratura.cl/el-guason-la-invencion-de-la-soledad/",
    "https://www.cineyliteratura.cl/guason-de-todd-phillips-las-claves-del-filme-que-remece-la-cartelera-mundial/",
    "https://www.cineyliteratura.cl/debate-joker-un-largometraje-controversial-y-de-multiples-interpretaciones/",
    "https://cinecapsdigest.wordpress.com/4334-2/",
    "http://www.cinedergi.com/2020/03/26/kac-kisiyi-oldurdum-duslerimde-joker/",
    "http://www.cinedump.com/reviews/2020/1/6/joker-2019",
    "https://www.cinefacts.it/cinefacts-articolo-432/joker-di-todd-phillips-ride-bene-chi-ride-ultimo-recensione-venezia-76.html",
    "https://cinefacts.it/cinefacts-articolo-472/joker-la-spirale-malata-di-una-splendida-illusione-recensione.html",
    "https://cinefilesreviews.com/2019/10/04/joker-2019-movie-review/",
    "https://www.cinefilia.blog/2019/10/critica-pelicula-joker.html",
    "https://www.cinefilos.it/tutto-film/recensioni/joker-joaquin-phoenix-410742",
    "https://cinemaaxis.com/2019/09/11/tiff-2019-joker/",
    "http://cinemababel.com/everything-old-is-new-in-joker/",
    "https://movie-reviews.cinemaclips.com/2019/10/joker.html",
    "http://cinemacomcritica.com.br/2019/10/coringa/",
    "https://cinemissile.blogspot.com/2020/01/joker-todd-phillips-2019.html",
    "https://cinemaemcena.com.br/critica/filme/8494/coringa",
    "https://www.cinemaparapromedios.com.mx/2019/joker-2019/",
    "http://www.cinemasmack.com/in-theaters-review-joker/",
    "https://www.cinema7arte.com/joker-uma-intensidade-estetica-descoisificante/",
    "https://cinematelevisionmusic.wordpress.com/2019/10/22/phillips-joker-2019/",
    "https://cinemagavia.es/pelicula-joker-critica/",
    "https://cinemagavia.es/joker-2019-critica-pelicula/",
    "https://cinemagavia.es/joker-joaquin-phoenix-critica-pelicula/",
    "https://cinemagazine.nl/joker-2019-recensie/",
    "http://www.cinemagicon.com/gleeful-gritty-joker-is-arthouse-anarchy-triumphant-over-dull-diversion/",
    "https://cinemags.co.id/review-film-joker/",
    "https://www.cineman.ch/movie/2019/Joker/review.html#movie-detail-nav",
    "https://www.cinemarvellous.com/2019/10/80010-joker-2019.html",
    "https://www.cinematik.it/2019/08/joker",
    "https://www.cinematographe.it/recensioni/joker-recensione-film-joaquin-phoenix/",
    "https://www.cinemavenger.com/joker.html",
    "https://cinephil.home.blog/films-by-date-seen/2019-2/october-2019/joker/",
    "https://cinergiaonline.com/cine/review-guason-joker/",
    "http://cinetariz.blogspot.com/2019/10/review-joker.html",
    "https://cine-vue.com/2019/08/venice-2019-joker-review.html",
    "https://www.cinopsis.be/film/joker/",
    "http://cinreservas.com/desafios-tecnicos/el-desafio-tecnico-de-joker-2019/",
    "https://cinreservas.com/apreciacion-visual/de-arthur-fleck-a-joker-una-evolucion-visual/",
    "https://cinedweller.com/movie/joker-la-critique-du-film/",
    "https://www.cineserie.com/critiques/cine/joker-quand-gotham-et-lamerique-enfantent-du-joker-2837556/",
    "https://www.cine-histoire.ca/film/joker/",
    "http://www.cinefilic.com/2019/10/joker.html",
    "http://cinesthesiac.blogspot.com/2019/10/sorry-for-laughing-joker.html",
    "https://www.citazine.fr/article/joker-douloureux-eclats-de-rire",
    "https://citymagazine.rs/kultura/film-tv/da-li-je-dzoker-film-godine-kriticki-osvrt-na-trenutno-najveci-hit-u-svetskim-i-srpskim-bioskopima/?fbclid=IwAR27CkKi2cQzW1T00XuT_kMjfTqKXtgtkYRRjdvl4_LnVY-MJnLNoiREm1w",
    "https://www.colesmithey.com/reviews/2020/01/joker.html",
    "http://colourlessopinions.com/2019/09/joker-2019-movie-review-malaysia.html",
    "https://www.youtube.com/watch?v=tivJDPe8iL0",
    "https://www.comic.de/2020/04/joker-batman-das-diabolische-duo-und-seine-identitaetskonflikte/",
    "https://www.comic.de/2019/10/der-gesellschaftsvertrag-ist-aufgekuendigt-joker/",
    "https://www.commonsensemedia.org/movie-reviews/joker",
    "https://www.companhiacinefila.pt/2019/10/joker-em-analise.html",
    "http://www.correcamara.com.mx/inicio/int.php?mod=noticias_detalle&id_noticia=7615&fbclid=IwAR33-MLf6II8tCShLww1nqwox08ZA_wlLUN-jeu4FZAusvnnR-GKUFqLtLE",
    "https://www.correcamara.com.mx/inicio/int.php?mod=noticias_detalle&id_noticia=8640",
    "https://www.correcamara.com.mx/inicio/int.php?mod=noticias_detalle&id_noticia=8748",
    "https://countercultureuk.com/2019/10/26/joker/",
    "https://www.youtube.com/watch?v=XpjExlM6nvM",
    "https://www.critic.de/film/joker-12981/",
    "https://criticafterdark.blogspot.com/2019/10/joker-todd-philips-2019.html",
    "https://thecriticalcritics.com/reviews/movie-review-joker/",
    "https://crookedmarquee.com/review-joker/",
    "https://www.crpwrites.com/joker-review",
    "https://crypticrock.com/joker-movie-review/",
    "http://criticos.com.br/?p=11781&cat=1",
    "https://cualia.es/critica-joker-todd-phillips-2019/",
    "https://cuatrobastardos.com/2019/10/01/review-joker-2019/",
    "https://www.cubaencuentro.com/cultura/articulos/entre-la-realidad-y-el-delirio-336160",
    "http://www.culledculture.com/joker-the-most-offensive-white-people-movie-at-the-oscars-since-la-la-land/",
    "http://www.culledculture.com/where-are-the-clowns-there-ought-to-be-clowns-send-in-joker/",
    "https://cultfaction.com/2019/10/06/review-joker-2019/",
    "http://cultprojections.com/essentialviewing/joker",
    "https://cultura.id/joker-spoiler-review/",
    "https://cultura.id/joker-review/",
    "https://culturedvultures.com/joker-review/",
    "https://culturess.com/2019/10/04/joker-review-joaquin-phoenix-cant-save-desperate-act-pretension/",
    "https://gofatherhood.com/2019/10/film-review-joker/",
    "https://www.daily-movies.ch/joker-naissance-dune-icone",
    "https://darkmatt.blogspot.com/2019/10/matt-puts-on-happy-face-joker-review.html",
    "https://darrens-world-of-entertainment.blogspot.com/2019/10/joker-film-review.html",
    "https://dasfilmfeuilleton.de/joker-kritik/",
    "https://www.dbazi.com/1398/09/08/%db%8c%d8%a7%d8%af%d8%af%d8%a7%d8%b4%d8%aa%db%8c-%d8%a8%d8%b1-%d9%81%db%8c%d9%84%d9%85-joker/",
    "https://defilmblog.be/archive/2020/01/31/joker-2019-blu-ray-review.html/",
    "https://www.defilmkijker.com/2019/10/12/joker-2019-recensie/",
    "http://www.deprotagonisten.nl/recensies/joker/",
    "https://deep-red-radio.net/joker/",
    "https://www.denofgeek.com/us/movies/joker/283452/joker-review-joaquin-phoenix",
    "https://dennisschwartzreviews.com/joker/",
    "https://filmblogcast.wordpress.com/2019/11/08/folge-19-antihelden-joker/",
    "https://der-kinogaenger.blogspot.com/2020/01/joker-2019.html",
    "https://derzweifel.com/2019/10/09/joker-todd-phillips-recensione-joaquin-phoenix-la-vita-e-una-tragedia-o-una-commedia/",
    "http://www.derekwinnert.com/joker-2019-joaquin-phoenix-robert-de-niro-zazie-beetz-movie-review/",
    "https://necofobia1.wordpress.com/2019/10/08/comodin/",
    "https://www.destroythecomics.com/movies/joker-quick-review-comics-echoing-taxi-driver/",
    "https://dialmformovie.net/2019/10/13/todd-phillipsin-jokerine-gostergebilimsel-bir-bakis/",
    "https://dienachtderlebendentexte.wordpress.com/2019/10/08/joker/",
    "https://www.dmovies.org/2019/10/02/joker/",
    "http://distintamirada.co/?p=17235",
    "https://www.doblu.com/2020/01/03/joker-4k-uhd-review/",
    "https://doctorofmovies.com/2019/10/24/review-joker-2019/",
    "https://www.doublefeaturepreachers.com/davids-reviews/joker-a",
    "https://www.doublefeaturepreachers.com/shannons-reviews/joker-2019",
    "https://www.douxreviews.com/2019/10/joker.html",
    "https://dragonladyfiles.com/2019/10/16/joker-dcs-villain-in-a-darkly-real-world-%e2%98%86%e2%98%86%e2%98%86%e2%98%86/",
    "https://www.dreadcentral.com/reviews/310600/tiff-2019-joker-review/",
    "https://dvd-fever.co.uk/joker-on-blu-ray-the-dvdfever-review-joaquin-phoenix/",
    "http://dvdsleuth.com/JokerReview/",
    "https://www.dvdizzy.com/joker-film.html",
    "https://echoboomer.pt/critica-joker/",
    "https://www.edb.co.il/blog/archives/25391",
    "https://www.edgemedianetwork.com/entertainment/movies/reviews//285200",
    "https://www.elantepenultimomohicano.com/2019/09/critica-joker.html",
    "https://elcontraplano.com/2019/09/28/joker-villano-o-victima/",
    "https://elgolocine.wordpress.com/2020/06/01/joker-elude-el-tema-central-de-las-actuales-protestas-en-eeuu-el-racismo/",
    "https://www.electric-shadows.com/joker/",
    "https://elementsofmadness.com/2019/10/03/joker/",
    "https://www.elitisti.fi/arvostelu/2019/10/joker-2019-todd-phillips",
    "https://www.youtube.com/watch?v=_Hdza3s89MM",
    "https://emmaatthemovies.blogspot.com/2019/11/joker-spoilers-movie-review.html",
    "https://ew.com/movie-reviews/2019/09/10/joker-review/",
    "https://www.epd-film.de/filme/joker",
    "https://erikkersten.nl/joker/",
    "http://www.escapeintofilm.com/home/joker-film-review",
    "https://www.escapistmagazine.com/v2/joker-review-escape-to-the-movies/",
    "https://www.youtube.com/watch?v=S_ThW_Rs80A&feature=youtu.be",
    "https://espiamodelo.com/2020/02/07/10-razones-para-amar-joker-de-todd-phillips-especial-premios-oscar-2-020-iii/",
    "https://eternalitytan.com/2019/10/06/joker-2019/",
    "http://www.everymoviehasalesson.com/blog/2019/10/movie-review-joker",
    "http://everysingledaymissing.blogspot.com/2019/10/movie-rave-joker.html",
    "hhttps://expelledgreymatter.blogspot.com/2020/09/joker-2019.html",
    "https://explosionnetwork.com/movie-reviews/joker-review",
    "https://www.eyeforfilm.co.uk/review/joker-2019-film-review-by-angus-wolfe-murray",
    "https://medium.com/eyes-wide-open/every-other-best-picture-oscar-nominee-deserves-to-beat-joker-9fa3cfc40068",
    "https://ezadar.rtl.hr/ostalo/intervjui/3576375/joker-novo-ime-za-remek-djelo/?ticker_type=latest_news",
    "http://www.fantasticmovies.de/joker-kritik",
    "http://feelinfilm.com/movie-review-joker/",
    "http://screenfellows.com/2019/10/davids-watch-diary-october-2019/",
    "https://fermouart.gr/2019/10/13/joker-2019/",
    "https://fifthabouttheseventh.com/2019/10/08/joker-2019/",
    "https://film-authority.com/2019/09/30/joker-2019/",
    "https://filmblitz.org/joker-2019/",
    "https://film-book.com/film-review-joker-2019-a-nihilistic-villain-given-a-sympathetic-backstory-depth-in-a-near-miss-game-changer/",
    "http://www.filmboy.gr/2019/10/joker-2019.html",
    "https://film-bunker.com/2019/09/27/joker-review/",
    "https://www.filmdude.com.au/review/joker",
    "http://www.filmfestivaltoday.com/film-reviews/film-review-this-joker-is-all-hole-and-no-ace",
    "https://www.filmfreakcentral.net/ffc/2019/09/tiff-2019-joker.html",
    "https://thefilmfrenzy.com/2019/10/04/joker-the-tears-of-a-clown/",
    "https://www.filmgeekreviews.com/2021/10/joker-film-review.html",
    "https://www.filmgrouch.com/reviews/drama/joker/",
    "https://filmmusiccentral.com/2019/10/06/soundtrack-review-joker-2019/",
    "https://filmobsessive.com/film/new-releases/coming-soon-joker/",
    "https://filmparadiset.se/joker-2019-recension/",
    "https://filmplanetreviews.wordpress.com/2019/10/14/kritiki-gia-to-joker/",
    "https://filmracket.com/joker/movie-review",
    "https://www.filmreviewdaily.com/all-reviews/joker",
    "http://filmreviewsbymark.com/2019/10/05/joker/",
    "http://filmsnobreviews.com/2019/10/review-joker/",
    "https://www.filmtotaal.nl/recensie/13757",
    "https://www.filmvandaag.nl/recensies/824-joker",
    "https://film-authority.com/2024/10/12/joker/",
    "http://film-forward.com/crime/joker",
    "https://www.film-rezensionen.de/2019/10/joker/",
    "http://www.filmaluation.com/joker.html",
    "https://www.filmfutter.com/joker/",
    "https://www.filmhuismechelen.be/review/joker/",
    "https://filmliefhebber.com/review-joker/",
    "https://www.filmmelier.com/pt/br/film/7309/coringa",
    "https://filmmierenneukers.nl/recensie-joker-2019-joaquin-zet-dc-terug-op-de-kaart/",
    "http://www.filmofiel.nl/2019/10/joker-2019/",
    "https://filmotomy.com/film-road-to-halloween-joker-2019/",
    "https://filmreporter.de//kino/87052-Joker",
    "https://www.filmsfantastiques.com/2021/12/joker-2019/",
    "http://filmskerecenzije.com/joker-2019/",
    "https://filmski-koticek.blogspot.com/2019/10/joker-2019.html",
    "http://www.filmstarts.de/kritiken/258374/kritik.html",
    "https://filmsucht.org/joker/",
    "https://www.filmtett.ro/cikk/bunos-e-vagy-aldozat-joker-kritika/",
    "https://www.filmy.gr/movies-database/joker/#1569924886979-f728b42b-50fc",
    "https://www.filmy.gr/movies-database/joker/#1677951231316-5083140f-8551",
    "https://flickdirect.com/movie-review/2348/the-joker/movie.ashx",
    "https://flickdirect.com/flickvision/2150/watch-movie/home-video-review/joker/streaming-video.ashx",
    "https://www.flickeringmyth.com/2019/09/toronto-international-film-festival-2019-joker-review/",
    "https://www.flickfeast.co.uk/reviews/film-reviews/joker-film-review/",
    "https://www.flickreel.com/joker-review/",
    "https://www.flicks.co.nz/reviews/joker-feints-toward-edginess-but-comes-off-a-little-stale/",
    "https://flixchatter.net/2019/10/03/flixchatter-review-joker-2019/",
    "https://blog-fluxkompensator.de/joker-2019-filmkritik",
    "http://foritismansnumber.blogspot.com/2020/02/joker-2019.html",
    "https://www.forbes.com/sites/markhughes/2019/08/31/review-joker-is-one-of-the-best-films-of-2019/#3458bcda29c0",
    "https://www.fwweekly.com/2019/10/09/no-laughing-matter-2/",
    "https://frdennismoviereviews.blogspot.com/2019/10/joker-2019.html",
    "https://frammentidicinema.com/2019/10/11/joker-di-todd-phillips/",
    "http://frasesdecineparaelrecuerdo.blogspot.com/2019/10/frases-pelicula-joker-todd-phillips.html",
    "http://frombeyond.se/joker-2019/",
    "https://furyosa.com/joker-critique/",
    "https://g-rafa.co.il/%d7%91%d7%99%d7%a7%d7%95%d7%a8%d7%aa-%d7%a1%d7%a8%d7%98-%d7%92%d7%95%d7%a7%d7%a8-%d7%98%d7%99%d7%a8%d7%95%d7%a3-%d7%a7%d7%95%d7%9c%d7%a0%d7%95%d7%a2%d7%99-%d7%92%d7%90%d7%95%d7%a0%d7%99/",
    "http://www.gamechannel.hu/cikk/cinemachannel/joker",
    "https://gamerheadquarters.com/movies/joker-review.html",
    "http://www.gandolcine.com/2019/10/joker-2019.html",
    "https://www.gazeteduvar.com.tr/yazarlar/2019/10/04/joker-bu-isler-sakaya-gelmez/",
    "https://geekculture.co/geek-review-joker/",
    "https://www.geek-germany.de/review-film-joker/",
    "https://www.geekloid.co.il/joker-review/",
    "https://geeksandgamers.com/review-joker-2019/",
    "https://www.getonmydamnlevel.com/blog/2019/10/7/movie-review-joker-2019",
    "https://www.youtube.com/watch?v=TIhrFfmKIic",
    "http://gonewiththetwins.com/new/joker-2019/",
    "https://goodefficientbutchery.blogspot.com/2019/10/in-theaters-joker-2019.html",
    "https://tipo-goodtalking.blogspot.com/2019/09/joker.html",
    "https://gunaxin.com/joker-movie-review",
    "https://blog.dnevnik.hr/stankagj/2019/11/1632264247/moje-videnje-filma-joker.html",
    "https://www.haberturk.com/yazarlar/mehmet-acar/2527738-korkuyla-beklenen-film-gosterimde",
    "https://www.movieswithhart.com/post/joker-folie-%C3%A0-deux-2024-review",
    "https://happyphantomblog.wordpress.com/2019/10/06/genesis-de-un-monstruo/",
    "https://www.hardsensations.com/2019/10/eine-offene-wunde-notizen-zum-joker/",
    "http://www.harmonicacinema.com/joker/",
    "https://hcmoviereviews.wordpress.com/2019/09/30/joker/",
    "https://www.hedmarkfilms.com/joker-birth-of-a-clown-prince/",
    "https://www.heyuguys.com/joker-review/",
    "https://highdefdiscnews.com/2020/01/13/joker-4k-uhd-blu-ray-review/",
    "https://www.highonfilms.com/joker-analysis-2019/",
    "https://www.highonfilms.com/joker-2019-review/",
    "https://hive.blog/the/@the-jedi/the-joker-2019-is-an-incredible-film-and-joaquin-phoenix-absolutly-kills-it-past-perfection",
    "https://hojeviviumfilme.blogspot.com/2019/10/critica-joker-2019.html",
    "https://www.tamilhollywoodreviews.com/2020/08/joker-2019.html",
    "http://hoopla.nu/films/joker",
    "http://horrorhabit.blogspot.com/2019/10/joker-2019.html",
    "https://hotair.com/archives/ed-morrissey/2019/10/12/film-review-joker/",
    "https://howtowatchamotionpicture.blogspot.com/2019/10/joker.html",
    "https://hubpages.com/entertainment/Joker-2019-Movie-Review",
    "https://www.huffpost.com/entry/joker-review-joaqun-phoenix-todd-phillips_n_5d7bfddfe4b00d6905988775",
    "https://www.humonegro.com/cine/comentarios/guason/",
    "https://www.hurriyet.com.tr/kelebek/keyif/joker-modern-ve-alternatif-bir-gulen-adam-biyografisi-gibi-41328287",
    "https://www.hurriyet.com.tr/yazarlar/ugur-vardan/yakarsa-dunyayi-joker-yakar-41344014",
    "https://www085.blogspot.com/2019/10/joker-2019-review.html",
    "http://www.ikassenshow.dk/2019/10/i-kassen-548-joker-2019.html",
    "https://imjeffreyrex.com/2019/10/03/review-joker-2019/",
    "https://ifyouwantthegravy.wordpress.com/2019/10/04/joker-review/",
    "http://www.illuminedillusions.com/Joker.htm",
    "https://www.youtube.com/watch?v=3hXROvGGF8k&feature=youtu.be",
    "https://funxton.wordpress.com/2019/11/10/joker/",
    "https://www.intofilm.org/films/reviews/864065",
    "https://intoscreens.com/2019/10/03/review-joker/",
    "https://irishcinephile.com/2020/06/14/top-100-films-of-the-2010s-31-joker-2019/",
    "https://irishcinephile.wordpress.com/2019/10/06/film-review-joker/",
    "https://www.irishfilmcritic.com/movie-review-dc-delivers-big-time-with-joker/",
    "https://itsjustamovie.com/movieindex#/joker/",
    "https://www.wcbe.org/post/joker",
    "https://neoversionsix.medium.com/the-joker-2019-is-an-incredible-film-and-joaquin-phoenix-absolutly-kills-it-past-perfection-5c115fa92869",
    "https://jasonsmovieblog.com/2020/01/02/joker-2019-review/",
    "https://www.jdbrecords.com/2019/10/joker.html",
    "https://www.youtube.com/watch?v=0tsdOo_wO44&t=899s",
    "https://www.youtube.com/watch?v=PJORkfmnmdY",
    "https://jerrysaravia.blogspot.com/2021/02/dont-smile.html",
    "https://www.jilsblog.com/2019/10/filmkritik-joker/",
    "https://www.youtube.com/watch?v=V34S6COZUm0",
    "https://www.joblo.com/movie-news/review-joker-tiff-2019",
    "https://www.johnnypunish.com/2019/10/review-joker-goes-crazy-bludgeons-entertainment/",
    "https://www.joshiesworld.com/joker/",
    "https://www.karanliksinema.com/2019/10/joker-2019-film-elestirisi.html",
    "https://keithlovesmovies.com/2019/09/20/tiff-2019-joker-review/",
    "https://kids-in-mind.com/j/joker-parents-guide-movie-review-rating.htm",
    "https://www.kinofilmwelt.de/filme/details/joker",
    "https://www.youtube.com/watch?v=LGFU9Q1MMZo&t=4s",
    "https://www.kino-zeit.de/film-kritiken-trailer/joker-2019",
    "https://www.kinofans.com/Filmkritiken/Joker-Filmkritik-Ein-Film-den-nur-Kritiker-hassen-koennen-E95762.htm",
    "https://www.kinowetter.ch/movie/4991/joker/",
    "https://www.kpbs.org/news/2019/oct/03/joker-wannabe-scorsese/",
    "https://www.kulturbunkeren.dk/joker/",
    "https://www.kulturbunkeren.dk/tiff19-joker/",
    "https://kunstundfilm.de/2019/10/joker/",
    "https://www.bizjournals.com/losangeles/news/2019/10/04/flick-picks-joker-is-no-laughing-matter.html",
    "https://www.lacabecita.com/2019/10/critica-joker/",
    "https://lasaveurdesgoutsamers.com/2019/10/17/joker-todd-phillips-2019/",
    "https://www.laweekly.com/review-joaquin-phoenix-isnt-clowning-around-in-joker/",
    "https://www.lashorasperdidas.com/index.php/2019/10/04/joker/",
    "https://www.youtube.com/watch?v=VikNTWmfycg&feature=youtu.be",
    "https://www.rayonvertcinema.org/joker-todd-phillips/",
    "https://www.leinwandreporter.com/2019/review-joker-kino/",
    "http://leitmovie.it/joker",
    "https://leschroniquesdecliffhanger.com/2019/10/07/joker-critique/",
    "https://moviemovesme.com/2019/09/16/tiff-2019-film-review-joker-2019/",
    "https://letsgotothemovies.co.uk/2019/10/05/joker-2019-review/",
    "https://www.lifeinthedark.film/post/joker",
    "http://www.linkinmovies.it/cinema/in-sala/8145-joker-recensione-venezia-76-concorso",
    "https://lipercubo.it/joker-t-phillips-2019.html",
    "https://www.latimes.com/entertainment-arts/movies/story/2019-10-03/joker-warner-bros-premiere-controversy-joaquin-phoenix",
    "https://www.lostincinema.it/recensioni/joker-recensione/",
    "https://loudandclearreviews.com/joker-review/",
    "https://lovepopcornreviews.com/review-joker-2019/",
    "https://lylesmoviefiles.com/2019/10/02/joker-movie-review-no-laughing-or-entertaining-matter/",
    "https://www.madmass.it/joker-recensione/",
    "https://maddwolf.com/new-in-theaters/the-man-who-laughs/#sthash.GjZ3yf83.dpbs",
    "http://www.alunauwie.com/2020/07/joker-all-i-have-are-negative-thoughts.html",
    "https://madifonbyfashion.blogspot.com/2020/02/a-smokeshow.html",
    "https://www.youtube.com/watch?v=pxXRymkYJcM",
    "https://marcfusion.com/2020/01/15/joker-2019/",
    "https://www.marieclaire.co.uk/entertainment/tv-and-film/must-see-films-september-707952",
    "http://www.markreviewsmovies.com/reviews/J/joker-2019.htm",
    "https://markedmovies.org/2019/11/20/joker/#more-9864",
    "http://maroonersrock.com/joker-review-film/",
    "http://www.mattsmoviereviews.net/movie-critic-reviews/joker.html",
    "http://mcbastardsmausoleum.blogspot.com/2020/01/joker-2019-4k-ultrahd-review.html?m=1",
    "https://www.mediaversityreviews.com/film-reviews/2019/10/6/joker",
    "https://meduza.io/feature/2019/09/01/dzhoker-todda-fillipsa-mrachneyshaya-predystoriya-klouna-ubiytsy-kotoraya-stanet-klassikoy",
    "https://melcon.blog/2019/10/07/an-apology-for-the-devil/",
    "http://metacultura.com.ar/la-risa-que-duele/",
    "http://metacultura.com.ar/ese-chiste-ya-no-da-gracia/",
    "https://www.milliyet.com.tr/yazarlar/nil-kural/altin-aslan-prestiji-tehlikeli-maddeye-karsi-6045707",
    "https://www.modernmyths.nl/joker/",
    "https://www.youtube.com/watch?v=lu7JeqQPILU&list=PLRD7N-Zrj2DMOLTG7t9E-vJo35BzeTwVG&index=119",
    "https://www.youtube.com/watch?v=lu7JeqQPILU&list=PLRD7N-Zrj2DMOLTG7t9E-vJo35BzeTwVG&index=119",
    "https://montasefilm.com/review-joker/",
    "https://www.moveitmag.gr/tainies/joker/61390",
    "https://www.moviebreak.de/film/untitled-joker-origin-movie",
    "https://www.moviequotesandmore.com/joker-2019-movie-review-1/",
    "https://www.moviequotesandmore.com/joker-2019-movie-review/",
    "http://josedlaura.blogspot.com/2019/10/joker-excepcional-actuacion-de-joaquin.html",
    "https://www.moviewolf.de/filme/kategorie-j/joker-2019.html",
    "https://moviebabblereviews.com/2019/10/10/joker-joaquin-phoenix-dc-comics-taxi-driver-king-of-comedy/",
    "http://moviefreak.com/joker-2019-movie-review/",
    "https://moviemag.ir/cinema/movie-reviews/world/24933-%D9%86%D9%82%D8%AF-%D9%88-%D8%A8%D8%B1%D8%B1%D8%B3%DB%8C-%D9%81%DB%8C%D9%84%D9%85-%D8%AC%D9%88%DA%A9%D8%B1-joker",
    "http://moviemansguide.com/main/2020/01/review-joker-4k-bd/#more-22638",
    "http://www.moviementarios.com/critica-joker/",
    "http://moviesnoir.blogspot.com/2019/10/joker.html",
    "https://moviesandshakers.com/joker/",
    "http://www.moviesinfocus.com/review-todd-phillips-joker-is-essential-cinema/",
    "http://www.moviesltd.gr/2019/10/joker-review.html",
    "https://youtu.be/wFjFK10J2SA",
    "https://movieweb.com/mark-hamill-joker-movie-review/",
    "https://mrgeekyblog.wordpress.com/2019/11/14/joker-2019/",
    "https://www.facebook.com/photo/?fbid=2440990916113282&set=a.1539656506246732",
    "https://mrmoviefilmblog.com/2019/09/29/joker-2019/",
    "https://mrmoviefilmblog.com/2019/10/05/joker-ii-2019/",
    "https://www.msbreviews.com/movie-reviews/joker-spoiler-free-review",
    "https://www.mtrnetwork.net/joker-isnt-as-audacious-as-it-thinks-it-is/",
    "https://www.muchepic-review.com/2019/12/joker2019ReviewDanAnalisis.html",
    "https://mydirtsheet.com/2019/10/03/joker-review/",
    "https://www.myfilm.gr/v2/site-map/blogreviews/aggelos-polydoros/item/4108-joker-2019",
    "https://www.myfilm.gr/v2/site-map/blogreviews/giannis-efthymiadis/item/4299-joker-2019",
    "https://www.myfilm.gr/v2/site-map-2/blogreviews/item/4478-joker-i-tainia-tis-xronias",
    "https://numanserteli.blogspot.com/2019/10/joker.html",
    "https://n3rdcore.it/joker-recensione-film-joaquin-phoenix/",
    "https://youtube.com/watch?v=F8AluOsytOQ",
    "https://www.nationalreview.com/2019/10/movie-review-joker-honest-treatment-of-madness/",
    "https://www.nationalreview.com/2019/10/movie-review-joker-most-unsettling-comic-book-movie/",
    "https://www.nationalreview.com/magazine/2019/10/28/joker-a-violent-noxious-scorsese-rip-off/",
    "https://nummtheory.blogspot.com/2019/11/joker-2019.html",
    "https://negativespace.blogger.de/stories/2735227/",
    "https://nenufaresefervescentes.blogspot.com/2019/11/joker.html",
    "https://neofilmshop.com/blogs/news/film-review-joker-2019-usa",
    "https://nerddimension.com/2019/10/13/joker-film-review/",
    "https://nerdnationmagazine.com/2019/10/18/film-review-joker-2019/",
    "https://nerdsbeforebirds.com/2020/02/09/85-joker/",
    "https://nerdsmagazine.com/joker-movie-review-2019/",
    "https://netnevesht.com/joker-2019-review/",
    "https://www.netzwelt.de/filme/172815-joker-wahnsinnig-gut-einfach-nur-wahnsinnig.html",
    "https://observer.com/2019/10/joker-review-joaquin-phoenix-rex-reed/",
    "https://nighthawknews.wordpress.com/2020/04/19/the-history-of-the-academy-awards-best-picture-2019/",
    "https://nomajesty.com/joker-review-2019/",
    "https://noguiltfangirl.com/monday-movie-minute-is-joker-for-kids-jokermovie/",
    "https://www.notonlyhollywood.com/joker-2019/",
    "https://notesaboutfilms.blogspot.com/2019/10/joker-based-on-work-by-bob-kane-bill.html",
    "https://obelde.com/viewtopic.php?f=136&t=1431",
    "https://www.ocmoviereviews.com/movie-reviews/joker-review/",
    "https://www.ocmoviereviews.com/movie-reviews/joker-review-2/",
    "https://ohthatfilmblog.com/2019/10/07/joker-2019/",
    "https://www.okayplayer.com/originals/new-joker-movie-controversy-black-people-review.html",    
    "https://theclock.blog/2019/09/14/joker-tiff-2019-review/",
    "https://www.on-magazine.co.uk/arts/film-reviews/joker-2019/",
    "https://bob-the-movie-man.com/2019/10/15/one-manns-movies-film-review-joker-2019/",
    "https://oneroomwithaview.com/2019/10/05/joker-review/",
    "http://movie-freak.be/2019/11/joker-2019/",
    "https://www.oqver.net/critica/coringa",
    "http://www.oscarboy.com/2019/10/07/joker/",
    "http://outtakemag.co.uk/reviews/2019/10/05/joker-review-joaquin-phoenix/",
    "https://overtheshoulder129848657.wordpress.com/2021/03/26/joker-why-did-the-mentally-ill-loner-cross-the-road/",
    "https://panandslam.com/2019/10/06/nihilistic-joker-is-taxi-driver-with-face-paint-joaquin-phoenix-is-the-only-redeeming-quality/",
    "https://pandaschoice.com/criticas/2019/10/joker-2019/",
    "https://parentpreviews.com/movie-reviews/joker",
    "https://ageofthegeek.org/2019/10/11/joker-the-porosity-of-joaquin-phoenix-%e2%98%86%e2%98%86%e2%98%86%e2%98%86/",
    "https://www.youtube.com/watch?v=MxLZv2qdlUI",
    "https://paullevinson.blogspot.com/2020/05/joker-fantasy-and-canon.html",
    "https://www.youtube.com/watch?v=ry89RM-UHy0&feature=youtu.be",
    "https://www.pcgalaxy.co.il/joker-solo-movie-dc-full-movie-review/",
    "https://pegadoalabutaca.wordpress.com/2019/10/09/guason/",
    "https://peggyatthemovies.com/2019/10/03/review-joker-2019-warner-bros/",
    "https://peliculaslatino.com/joker.html",
    "http://www.perasinema.com/joker-2/",
    "http://www.perun.hr/joker-joker",
    "https://pezzecritiche.wordpress.com/2019/10/12/joker-2019-recensione/",
    "https://philipbrasor.com/2019/10/02/review-joker/",
    "https://www.philm.dk/Movie/Detail?id=9232",
    "http://www.picturesthattalk.com/review.php?reviewid=3465",
    "https://youtu.be/GbJufOLSBQ0",
    "http://plainsimpletomreviews.com/2019/10/06/plain-simple-tom-reviews-joker-2019/",
    "https://pocmovie.com/blog/post/joker",
    "https://www.poffysmoviemania.com/joker-2019",
    "http://www.poltronapop.com.br/2019/10/critica-cinema-coringa-por-kal-j-moon.html",
    "https://popcinema.org/movie/joker-regista-todd-phillips-4d4l9?fbclid=IwAR3clcOH27I9kffSi_dWzviXhw4TjPodJflQd77I1yix87WGKiO3U6UhN1M",
    "https://popcinema.org/film/joker-regista-todd-phillips",
    "https://popculturemaniacs.com/joker-review/",
    "https://popculturethoughts.com/2020/01/22/joker-2019/",
    "https://www.portal-cinema.com/2019/11/critica-joker-2019.html",
    "https://www.portale7.com.br/2020/01/analise-do-filme-coringa.html",
    "https://pressplay.at/2019/10/08/joker/",
    "https://pressplaynews.net/2019/10/12/joker-review/",
    "http://www.pro-test.nl/blog/?p=3489",
    "https://produccioneslaviejaescuelapresenta.blogspot.com/2019/10/joker-el-ascenso-de-la-depresion-y-el.html",
    "https://projectedfigures.com/2019/10/02/joker-2019/",
    "http://proximatanda.com/cine/critica-joker-joaquin-phoenix-guason/",
    "https://pulp-movies.com/films/avis-joker-joaquin-phoenix-fait-son-one-man-show/14/",
    "https://www.publico.pt/2019/10/01/culturaipsilon/critica/homem-transparente-1888346",
    "https://qtasreviews.wordpress.com/2019/11/04/joker-g-l/",
    "https://quinlan.it/2019/09/02/joker/",
    "http://www.qwipster.net/2019/10/12/joker-2019/",
    "https://ars.rtvslo.si/2019/10/joker/",
    "https://www.radiotimes.com/news/film/2019-10-02/joker-film-review/",
    "https://www.youtube.com/watch?v=r5omRUomWuA",
    "https://randommovie.net/joker-2019/",
    "https://www.razorfine.com/movie-reviews/joker-2019/",
    "https://reactormag.com/thats-life-joker/",
    "https://readysteadycut.com/2019/10/04/joker-review-2019/",
    "https://readysteadycut.com/2019/10/05/joker-second-opinion-an-all-too-real-masterpiece-of-the-amoral/",
    "https://www.recenzijefilmova.com/joker-dzoker-2019-recenzija-filma/",
    "https://reelfilm.com/joker/",
    "http://reelhonestreviews.com/joker-a-vengeful-origin-story-that-hits-too-close-to-reality/?fbclid=IwAR1sBjGFvQJEQ52l_eb025fQoz8638dRCAto9i-ushjrgRNjBPSUK1AYBzQ",
    "https://reelreviewsoverbrews.com/2019/10/04/review-joker-2019/",
    "http://www.reeltalkreviews.com/browse/viewitem.asp?type=review&id=8298",
    "https://reeltalker.com/2020/01/14/movie-review-joker/",
    "https://www.reelingreviews.com/joker.htm",
    "https://residententertainment.com.au/joker-review-spoiler-free/",
    "https://revistapantallas.com/2019/10/10/critica-joker-una-radiografia-de-todo-lo-que-esta-mal-con-nuestra-sociedad/",
    "https://praxisrevista.com/2019/11/27/joker-o-la-broma-equivoca-de-hollywood/?fbclid=IwAR0A5GDT53iTe_BJgxkLtW4-AtaIhARY9cK1mblz7q6C0g5mVgDbECoe14k",
    "https://rioranchofilmreviews.blogspot.com/2019/10/joker.html",
    "https://www.youtube.com/watch?v=M5J78odc6Nw&list=PLFNYsCQU-KaMPQX8whHd19K6syiywZxwd&index=1",
    "http://www.rorypnm.com/2020/03/sinopsis-cerita-joker-review-film-2019.html",
    "https://roseshavethoughts.com/2019/10/09/film-review-joker/",
    "https://www.rosythereviewer.com/2019/10/joker-and-week-in-reviews.html",
    "https://www.youtube.com/watch?v=wNyd7uuDjpM",
    "http://www.ruthlessreviews.com/41280/joker/",
    "https://www.sabah.com.tr/cumartesi/2019/10/05/gothamda-bir-hayalet-dolasiyor",
    "http://www.sahmreviews.com/2019/10/thoughts-on-the-joker-movie.html",
    "https://www.youtube.com/watch?v=XBu44q7kF1c",
    "https://mag.sapo.pt/cinema/filmes/criticas/joker-joaquin-phoenix-e-o-tragico-palhaco-do-crime-em-filme-herdeiro-ao-trono-de-scorsese",
    "https://sarahgvincentviews.com/movies/joker/",
    "https://scannain.com/review/joker/",
    "http://scarythoughts.org/scary-thoughts-66-joker-with-guest-daniel-coffeen",
    "http://schlombies-filmbesprechungen.blogspot.com/2020/03/joker-2019-todd-phillips.html",
    "https://www.schokkendnieuws.nl/recensies/5700-joker",
    "https://schoolofrock.gr/joker-kritiki-tainias/",
    "http://www.scifimoviepage.com/joker-movie-review/",
    "https://www.scifinow.co.uk/reviews/joker-first-look-review-venice-film-festival-2019-joaquin-phoenix-puts-on-a-happy-face/",
    "https://screencomment.com/2019/10/movienews-joker/",
    "https://screenrant.com/joker-movie-2019-reviews/",
    "https://screenrealm.com/joker-movie-review-joaquin-phoenix/",
    "https://screenwaffle.com/2019/10/05/joker-review/",
    "https://www.screeningmovies.ch/2019/10/14/joker-am-abgrund-der-gesellschaft/",
    "http://www.searchmytrash.com/movies/joker(2019).shtml",
    "http://seattlerefined.com/lifestyle/review-joker",
    "http://www.segundotake.com/artigos/2019/10/6/joker",
    "https://sennhausersfilmblog.ch/2019/09/01/venedig-19-joker-von-todd-philips/",
    "https://www.sentieriselvaggi.it/joker-di-todd-phillips/",
    "http://kaist455.com/2019/10/02/joker-2019/",
    "https://www.sermosgaliza.gal/articulo/cultura/critica-de-cinema-jo/20191025072506085848.html",
    "https://ryancmcdonald.blogspot.com/2020/10/review-joker.html",
    "https://reelrundown.com/movies/Should-I-Watch-Joker",
    "https://www.showbizjunkies.com/movies/joker-review/",
    "https://silverscreenanalysis.com/joker-2019-review/",
    "https://simplylife.gr/pages/tainies/article/id/532",
    "https://www.slantmagazine.com/film/review-joker-is-a-punishingly-self-serious-mishmash-of-borrowed-parts/",
    "https://www.slashfilm.com/joker-review/",
    "https://slobodnadalmacija.hr/misljenja/cinemark/clanak/id/626311/joker-ubojiti-vicko-nadolijeva-ulje-na-vatru-kolektivne-psihoze",
    "https://society-reviews.com/2019/10/04/joker-review-discussion-an-amazing-movie-and-the-media-lie-that-almost-destroyed-it/",
    "http://www.solzyatthemovies.com/2019/09/10/toronto-2019-joker/",
    "http://sonic-cinema.com/movie/joker/",
    "https://www.scmp.com/lifestyle/entertainment/article/3025299/venice-2019-joker-film-review-joaquin-phoenix-excels-dc",
    "https://www.spielfilm.de/filme/3007206/joker/kritik",
    "https://www.spoilertv.com/2019/10/movies-joker-review.html",
    "https://spoilerpiece.com/2019/10/04/joker-5b-and-selections-from-the-boston-womens-film-festival-with-new-co-host-megan-kearns-episode-273/",
    "https://stack.com.au/film-tv/cinema-review/joker-review/",
    "https://www.strangemedia.org/new-blog/joker",
    "https://strikingfilmreviews.wordpress.com/2019/10/05/joker-2019/",
    "https://studentedge.org/article/movie-review-joaquin-phoenix-is-the-best-joker-ever",
    "https://sunshinestatecineplex.com/2019/10/07/review-phoenix-allows-joker-to-burn-bright-despite-a-lack-of-innovation/",
    "https://www.superheronews.gr/2019/10/joker-review.html",
    "https://www.youtube.com/watch?v=vVisJTp8DfM",
    "https://thevoid99.blogspot.com/2019/10/joker-2019-film.html",
    "https://svijetfilma.eu/recenzija-joker-joker-2019/",
    "https://www.revuesequences.org/2019/10/joker/",
    "https://t24.com.tr/yazarlar/atilla-dorsay/gotik-bilim-kurgudan-cagdas-trajediye-bir-sinema-zirvesi,24003",
    "http://www.tailslate.net/joker-is-no-laughing-matter/",
    "http://takeonecinema.net/2019/joker-review/",
    "https://talkingpulp.wordpress.com/2019/10/06/film-review-joker-2019/",
    "https://tanqeed.com/joker-review-by-sputnik/",
    "https://taquilladecine.com/critica-joker/",
    "https://www.terrorweekend.com/2019/10/joker-review.html",
    "http://tetartopress.gr/quot-joker-quot-mia-exairetiki-tainia-gia-tin-koinonia-ton-ipa-omos/",
    "https://www.thatmomentin.com/joker-review/",
    "https://theactionelite.com/joker-2019-review/",
    "https://kibsreviews.blogspot.com/2019/10/put-on-serious-face-joker-black-as.html",
    "http://thatdarngirlmovie.reviews/2019/10/06/jokermovie-movie-review/",
    "https://www.cinemadispatch.com/review/'Joker'-Review",
    "https://www.thecinemaholic.com/review-joker/",
    "https://www.youtube.com/watch?v=FDQoIZlprBU",
    "https://www.youtube.com/watch?v=viQXE1QMfVg",
    "http://thecriticalreel.com/joker/",
    "https://cultofghoul.blogspot.com/2019/10/joker-2019.html",
    "http://www.thedailyrotation.com/joker-review/",
    "http://www.thefilmfile.com/reviews/j/19_joker.htm",
    "http://thefreshfilms.com/Movies/joker_(2019).htm",
    "https://www.theguardian.com/film/2019/oct/03/joker-review-joaquin-phoenix-todd-phillips",
    "https://www.youtube.com/watch?v=k30ojPIHB6s&t=1s",
    "https://thehigharts.com/joker-film-review/",
    "https://thehigharts.gr/tzoker-todd-phillips/",
    "https://www.thehollywoodoutsider.com/joker-film-review/",
    "https://www.hollywoodreporter.com/review/joker-review-1235309",
    "https://theindependentcritic.com/joker",
    "https://johnnyalucard.com/2019/10/01/film-review-joker/",
    "https://www.lamplightreview.com/joker-movie-review-joaquin-phoenix/",
    "https://www.lamplightreview.com/second-opinion-joker-movie-review/",
    "https://macguff.in/film-reviews/joker-second-take/",
    "https://macguff.in/film-reviews/joker-2019/",
    "https://themacmahonian.weebly.com/reviews/youre-so-happy-you-could-kill-me",
    "https://themarckoguy.wordpress.com/2020/11/18/movie-review-joker-2019/",
    "https://www.themarysue.com/review-joker-masterclass-in-saying-nothing/",
    "http://www.thematinee.ca/joker/",
    "https://joethemnmovieman.com/2019/10/04/jkr/",
    "http://www.themoviebuff.net/2019/10/joker-r/",
    "https://moohooblog.blogspot.com/2021/08/family-plot.html",
    "http://themoviemensch.com/2019/10/04/joker-review-the-crown-prince-of-crime-gets-a-sensational-salute/",
    "https://moviemoustache.blogspot.com/2019/10/joker-average-guy-movie-review.html",
    "http://www.themoviewaffler.com/2019/09/joker-review.html",
    "http://www.the-other-view.com/joker2019.html",
    "http://www.parsinghaus.com/joker-review-by-haus/",
    "https://thepeoplesmovies.com/2020/03/film-review-joker-2019-2/",
    "https://thepeoplesmovies.com/2019/10/film-review-joker-2019/",
    "https://www.praguereporter.com/home/2019/10/4/movie-review-this-joker-aint-clowning-around",
    "https://thereelbits.com/2019/09/27/review-joker/",
    "http://www.theshiznit.co.uk/review/review-joker-discovers-the-magical-art-of-not-giving-a-fck.php",
    "https://theshyguyreviews.wordpress.com/2019/10/05/joker-movie-review/",
    "http://www.samdb.co.za/blogs/blog/2019/10/05/joker-review/",
    "http://stevethemovieman.proboards.com/thread/6325/joker-2019",
    "https://www.thestorytellersstudio.ca/reel-review-joker-2019",
    "https://theultimaterabbit.com/2020/01/10/joker-movie-and-blu-ray-review/",
    "https://www.theupcoming.co.uk/2019/10/01/joker-grit-drama-and-masterful-acting-that-could-set-a-new-era-of-comics-based-films-movie-review/",
    "https://thevideovacuum.blogspot.com/2019/10/joker-2019.html",
    "https://www.wsj.com/articles/joker-review-the-laughs-on-us-11570131914",
    "https://theweereview.com/review/joker",
    "https://www.thewrap.com/joker-film-review-joaquin-phoenix-robert-de-niro-dc-2019/",
    "https://www.thisisbarry.com/film/joker-ending-explained-2019-movie/",
    "https://thisislandrod.blogspot.com/2019/10/joker-2019.html",
    "https://throughthesilverscreen.com/2019/10/04/joker/",
    "https://www.tiempodecine.co/web/guason-de-todd-phillips/",
    "https://tilt.goombastomp.com/film/tiff-2019-joker-review/",
    "https://www.youtube.com/watch?v=AZSC7Lq9DbE",
    "https://tldrmoviereviews.com/2019/10/11/movie-review-joker/",
    "http://tonymacklin.net/content.php?cID=880",
    "http://www.toppraffel.se/2019/10/bio-joker.html",
    "https://torontodossier.wordpress.com/2019/09/11/joker-review-this-is-filmmaking-that-devastates-tiff-2019/",
    "http://treffpunkt-kritik.de/?id=2087",
    "http://trueviewreviews.com/review-joker-3/",
    "http://trueviewreviews.com/review-joker/",
    "https://www.tvmovie.de/news/joker-filmkritik-wer-zuletzt-lacht-hat-den-joker-108355",
    "http://filmreviewsfromtwoguysinthedark.blogspot.com/2019/10/joker.html",
    "https://www.ukfilmreview.co.uk/post/joker-film-review-uk",
    "https://unpoetpierdut.ro/joker-in-carti-pentru-a-deveni-filmul-anului-2019/",
    "https://www.uncut.at/movies/kritik.php?movie_id=13273",
    "https://www.universalmovies.it/joker-recensione-cinecomic-joaquin-phoenix/",
    "https://variety.com/2019/film/reviews/joker-review-joaquin-phoenix-todd-phillips-1203317033/",
    "https://www.youtube.com/watch?v=o470WrH8suU",
    "https://www.viewguide.com/movie_reviews/5017-joker",
    "https://viniloroto.wordpress.com/2019/10/05/joker-la-perdida-de-la-cordura/",
    "http://vodzilla.co/reviews/venice-film-festival-2019-reviews-joker/",
    "https://warped-perspective.com/index.php/2019/10/19/joker-2019/",
    "https://wegotthiscovered.com/movies/joker-review-tiff-2019/",
    "https://wehaveahulk.co.uk/joker-review/",
    "https://weliveentertainment.com/welivefilm/tiff-2019-joker-review/",
    "https://weliveentertainment.com/welivefilm/review-joker-twists-villainous-origins-unsettling-phoenix-performance-marshall/",
    "https://www.webtekno.com/joker-inceleme-h77366.html",
    "https://wessels-filmkritik.com/2019/10/04/joker/",
    "http://thecraggus.com/2019/10/10/joker-2019/",
    "https://whatwentrightwith.com/2019/10/04/what-went-right-with-joker/",
    "http://whatsworthseeing.com/joker-review/",
    "https://wherever-i-look.com/movies/joker-2019-summary-review-with-spoilers",
    "http://withoutyourhead.com/viewnews.php?autoid=110642",
    "http://www.wolframhannemann.de/archiv/201910.shtml#19100501",
    "https://worldfilmgeek.com/2020/01/14/joker-2019/",
    "https://www.youtube.com/watch?v=E9v-nw-NSjI",
    "https://yumuhole.com/2019/11/15/joker-movie-review/",
    "https://zawieszony.pl/en/the-white-narcissus-todd-phillips-joker-review/",
    "https://zawieszony.pl/bialy-narcyz-recenzja-jokera-todda-phillipsa/",
    "https://www.zekefilm.org/2019/10/03/joker-film-review/",


]


import sqlite3
import requests
from bs4 import BeautifulSoup
from langdetect import detect
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)  # INFO for general progress, DEBUG for detailed output

def create_db(db_name="reviews.db"):
    """Create a new SQLite database and the reviews table."""
    conn = sqlite3.connect(db_name)
    cursor = conn.cursor()
    
    # Drop the table if it already exists (to avoid conflicts)
    cursor.execute('DROP TABLE IF EXISTS reviews')

    # Create the reviews table with the 'date' column
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS reviews (
            id INTEGER PRIMARY KEY,
            title TEXT,
            date TEXT,
            original_language TEXT,
            review TEXT
        )
    ''')
    conn.commit()
    conn.close()

def add_date_column(db_name="reviews.db"):
    """Add the 'date' column to the reviews table if it's missing."""
    conn = sqlite3.connect(db_name)
    cursor = conn.cursor()
    
    try:
        cursor.execute('ALTER TABLE reviews ADD COLUMN date TEXT')
        conn.commit()
        print("Column 'date' added successfully.")
    except sqlite3.OperationalError as e:
        print(f"Error adding column: {e}")
    finally:
        conn.close()

def insert_review(db_name, title, date, language, review_text):
    """Insert a review into the SQLite database."""
    conn = sqlite3.connect(db_name)
    cursor = conn.cursor()
    
    # Insert the review into the table
    cursor.execute('''
        INSERT INTO reviews (title, date, original_language, review)
        VALUES (?, ?, ?, ?)
    ''', (title, date, language, review_text))
    
    conn.commit()
    conn.close()

def extract_review_text(soup):
    """Extract review text from different HTML elements."""
    review_text = ''
    
    # First attempt: <p> tags (common for plain text reviews)
    paragraphs = soup.find_all('p')
    review_text += '\n'.join([p.get_text(strip=True) for p in paragraphs if p.get_text(strip=True)])
    
    # Additional common places for reviews
    review_containers = [
        {'tag': 'div', 'class': 'review-text'},
        {'tag': 'div', 'class': 'review-body'},
        {'tag': 'span', 'class': 'review-content'},
        {'tag': 'section', 'class': 'review-section'},
        {'tag': 'div', 'itemprop': 'reviewBody'}
    ]
    
    # Iterate through all containers and extract text
    for container in review_containers:
        elements = soup.find_all(container['tag'], class_=container.get('class'), itemprop=container.get('itemprop'))
        for element in elements:
            review_text += '\n' + element.get_text(strip=True)
    
    return review_text.strip()

def scrape_and_save_reviews(url_list, db_name="reviews.db"):
    """Scrape reviews and save them to an SQL database."""
    
    # Uncomment the solution you want to use:
    
    # Solution 1: Drop and recreate the table with the correct schema
    create_db(db_name)
    
    # Solution 2: Add the missing 'date' column (uncomment if you don't want to drop the table)
    # add_date_column(db_name)
    
    error_count = 0  # To keep track of total errors
    for idx, url in enumerate(url_list, 1):  # Adding index for ID
        try:
            # Request the page content
            response = requests.get(url)
            response.raise_for_status()  # Will raise an exception for HTTP errors
            soup = BeautifulSoup(response.content, 'html.parser')

            # Extract the title - assuming the title is in the <title> tag
            title_tag = soup.find('title')
            title = title_tag.text.strip() if title_tag else 'No title found'

            # Extract the date of the review (looking for <time> or meta tags)
            date_tag = soup.find('time')
            date = date_tag.text.strip() if date_tag else 'Date not found'

            # Extract review text from various locations
            review_text = extract_review_text(soup)

            # Skip empty reviews
            if not review_text.strip():  # If review text is empty or contains only whitespace
                logging.warning(f"Review ID {idx} has no text, skipping.")
                continue

            # Detect language of the review text
            try:
                language = detect(review_text)
            except Exception as e:
                language = 'Unknown'
                logging.error(f"Error detecting language for Review ID {idx}: {e}")

            # Print the ID, title, date, language, and review text (if needed)
            print(f"\n--- Review ID: {idx} ---")
            print(f"Title: {title}")
            print(f"Date: {date}")
            print(f"Detected Language: {language}")
            print("Full review text:\n")
            print(review_text)

            # Insert the review into the database
            insert_review(db_name, title, date, language, review_text)

        except requests.exceptions.RequestException as e:
            error_count += 1
            # Print the error message to the console
            print(f"\nError retrieving {url}: {e}")

    print(f"\nTotal Errors Encountered: {error_count}")

scrape_and_save_reviews(url_list, db_name="reviews.db")
